import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "lenis/react";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Finovate - Financial Consulting + Risk Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.className} antialiased`}>
        <ReactLenis root />
        {children}
      </body>
    </html>
  );
}
